//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filtreler
    {
        public int ID { get; set; }
        public Nullable<int> SorguID { get; set; }
        public string ParametreTipi { get; set; }
        public string FiltreTipi { get; set; }
        public string ParemetreAdi { get; set; }
        public string ParametreDegeri { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public string KayitYapanKullanici { get; set; }
        public Nullable<System.DateTime> DuzenlemeTarihi { get; set; }
        public string DuzenlemeYapanKullanici { get; set; }
        public Nullable<bool> Silindi { get; set; }
        public Nullable<System.DateTime> SilinenTarih { get; set; }
        public string SilenKullanici { get; set; }
    }
}
