//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gorunumler
    {
        public int ID { get; set; }
        public string Kullanici { get; set; }
        public Nullable<int> SorguID { get; set; }
        public string SonucTipi { get; set; }
        public string EkAciklama1 { get; set; }
        public string EkAciklama2 { get; set; }
        public string EkAciklama3 { get; set; }
        public string EkAciklama4 { get; set; }
        public string EkAciklama5 { get; set; }
    }
}
