//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDReporting.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IDReportingEntities : DbContext
    {
        public IDReportingEntities()
            : base("name=IDReportingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Filtreler> Filtrelers { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }
        public virtual DbSet<Parametreler> Parametrelers { get; set; }
        public virtual DbSet<Sorgular> Sorgulars { get; set; }
        public virtual DbSet<Gorunumler> Gorunumlers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Yenilikler> Yeniliklers { get; set; }
        public virtual DbSet<Baglantilar> Baglantilars { get; set; }
    }
}
